
# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:3000"
#     env_file:
#       - ./backend/.env
#     volumes:
#       - ./backend:/app
#     depends_on:
#       - db

#   frontend:
#     build: ./frontend
#     ports:
#       - "5173:5173"
#     environment:
#       - VITE_API_BASE_URL=http://localhost:8000
#     volumes:
#       - ./frontend:/app
#     depends_on:
#       - backend
#     command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

#   db:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: backend
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3307:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
