
# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:3000"
#       - "8081:3001"
#     env_file:
#       - ./backend/.env
#     volumes:
#       - ./backend:/app:delegated
#     depends_on:
#       - db

#   frontend:
#     build: ./frontend
#     ports:
#       - "5173:5173"
#     environment:
#       - VITE_API_BASE_URL=http://localhost:8000
#     volumes:
#       - ./frontend:/app:cached
#     depends_on:
#       - backend
#     command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

#   db:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: backend
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3307:3306"

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: phpmyadmin
#     environment:
#       PMA_HOST: db
#       PMA_PORT: 3306
#     ports:
#       - "8080:80"
#     depends_on:
#       - db


